/* #define DISABLE_TIME_WIDTH_CHECK 1 */
/* #define DISABLE_ID_WIDTH_CHECK 1 */
/* #define DISABLE_NAME_WIDTH_CHECK 1 */
/* #define DISABLE_PERMISSION_CHECK 1 */
/* #define DISABLE_WP_WIDTH_CHECK 1 */
/* #define DISABLE_EGGS 1 */
